spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/shop
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1013147133735-j01tfa0ai92ui0cdlbfl0shquj5b09qk.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook:
            client-id: 6058431824255906
            client-secret: 8fbf42990f549b07de9f8fec80579dac
            scope:
              - email
              - public_profile
            redirect-uri: http://localhost:8989/login/oauth2/code/facebook
            #해당 주소는 Security 라이브러리가 관리하기 때문에 고정되어있음. 네이버는 고정되어있지 않지만, 규칙에 맞게 적어주는게 좋음. 페이스북, 구글 생략가능함.

          naver:
            client-id: BqLwzWiENtAyXuiCYgDi
            client-secret: lIdmrbLqi4
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8989/login/oauth2/code/naver #해당 주소는 Security 라이브러리가 관리하기 때문에 고정되어있음. 네이버는 고정되어있지 않지만, 규칙에 맞게 적어주는게 좋음.

          kakao:
            client-id: a67d1969e828bc47302124872164e46d
            redirect-uri: http://localhost:8989/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao

        #네이버는 provider 객체가 없기 때문에 Spring security가 사용할 수 없기 때문에 따로 provider 설정을 해줘야한다.   #     provider:
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize #네이버 로그인 창이 뜸. font에서 네이버링크로 요청했을 때, 최종적으로 호출되는 주소임.
            token-uri: https://nid.naver.com/oauth2.0/token             #토큰을 생성하기 위한 요청주소
            user-info-uri: https://openapi.naver.com/v1/nid/me          #프로필 정보를 받기 위한 요청주소
            user-name-attribute: response #회원정보를 json으로 받을 때 response라는 키 값으로 네이터가 리턴해준다.

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

mail:
  username:
  password:

#  mail:
#    host: smtp.naver.com
#    port: 465
#    username:
#    password:
#    properties:
#      mail.transport.protocol: smtp
#      mail.smtp.auth: true
#      mail.smtp.starttls.enable: ture
#      mail.debug: true
#      mail.smtp.ssl.enable: true
#      mail.smtp.ssl.trust: smtp.naver.com